{
 "title": "Hedgedoc",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "hedgedoc stats",
   "type": "stat",
   "description": "Hedgedoc notes stats",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "hedgedoc_notes", "legendFormat": "Notes" },
    { "expr": "hedgedoc_online_notes  ", "legendFormat": "Online notes " },
    { "expr": "hedgedoc_registered_users", "legendFormat": "Registered users" },
    { "expr": "hedgedoc_online_users", "legendFormat": "Online users" }
   ]
  },
  {
   "title": "Request duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum by (le) (rate(http_request_duration_seconds_bucket{job=\"application_metrics\"}[3m]))",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Process CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(process_cpu_user_seconds_total{job=\"application_metrics\"}[2m]) * 100",
     "legendFormat": "User CPU"
    },
    {
     "expr": "irate(process_cpu_system_seconds_total{job=\"application_metrics\"}[2m]) * 100",
     "legendFormat": "Sys CPU"
    }
   ]
  },
  {
   "title": "Event Loop Lag",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 10, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "nodejs_eventloop_lag_seconds{job=\"application_metrics\"}",
     "legendFormat": "hedgedoc"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "description": "Length of connection socket queue and connection busy indicates that realtime currently connecting",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "hedgedoc_connection_busy", "legendFormat": "connections busy" },
    {
     "expr": "hedgedoc_connection_socket_queue_length",
     "legendFormat": "socket queue length"
    }
   ]
  },
  {
   "title": "Process Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"application_metrics\"}",
     "legendFormat": "Process Memory"
    },
    {
     "expr": "nodejs_heap_size_total_bytes{job=\"application_metrics\"}",
     "legendFormat": "Heap Total "
    },
    {
     "expr": "nodejs_heap_size_used_bytes{job=\"application_metrics\"}",
     "legendFormat": "Heap Used"
    },
    {
     "expr": "nodejs_external_memory_bytes{job=\"application_metrics\"}",
     "legendFormat": "External Memory - {{instance}}"
    }
   ]
  },
  {
   "title": "Active Handlers/Requests Total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nodejs_active_handles_total{job=\"application_metrics\"}",
     "legendFormat": "Active Handler "
    },
    {
     "expr": "nodejs_active_requests_total{job=\"application_metrics\"}",
     "legendFormat": "Active Request"
    }
   ]
  }
 ]
}